{"uuid":"8b19d838-484a-425b-8caa-1f6d6106ec7b","historyId":"b64e87357edb459adf92ca33548fbd18","fullName":"ATB8xVrushabh.tests.PageObjectModel.SwagLabsPOM_Test.test_invalid_login_swag_labs","labels":[{"name":"package","value":"ATB8xVrushabh.tests.PageObjectModel.SwagLabsPOM_Test"},{"name":"testClass","value":"ATB8xVrushabh.tests.PageObjectModel.SwagLabsPOM_Test"},{"name":"testMethod","value":"test_invalid_login_swag_labs"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"SwagLabsProject"},{"name":"subSuite","value":"ATB8xVrushabh.tests.PageObjectModel.SwagLabsPOM_Test"},{"name":"host","value":"LAPTOP-MJR0TQGA"},{"name":"thread","value":"11104@LAPTOP-MJR0TQGA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"test_invalid_login_swag_labs","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Password is required]","trace":"java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Password is required]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat ATB8xVrushabh.tests.PageObjectModel.SwagLabsPOM_Test.test_invalid_login_swag_labs(SwagLabsPOM_Test.java:26)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that inavlid login shows error message","steps":[],"attachments":[],"parameters":[],"start":1737567321270,"stop":1737567328247}